services:
  pgsql-db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgsql-data:
    driver: local